name: Daily scrape Facebook page

on:
  schedule:
    - cron: "0 2 * * *"  # Chạy lúc 09:00 sáng giờ VN (2h UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install selenium gspread oauth2client pandas

    - name: Set up Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Run scraper
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: python scrape_fanpage.py
